### ISSUE TITLE
Look like this example doesn't work on latest zig anymore?

### ISSUE THREAD

**Issue by a12one** [kristoff-it/zig-redismodule#1]
Would be very helpful if this can be updated so that the barrier can be lower for new learner like me :smile: thanks

**Comment by kristoff-it** [comment]
Hi! True, I think I should simply archive this repo. The modern way of doing this is to just import `redismodule.h` in Zig. No fiddling required anymore.

**Comment by a12one** [comment]
Thanks for the insight, is there a chance you could update this example to make it work with the latest zig? It could be useful to lower the barrier for people like me (beginners). Much appreciated!
